{-# LANGUAGE TemplateHaskell #-}

module Orchestrator.AI.Client
  ( AiConfig (..),
    DiscoveredContent (..),
    ModelItem (..),
    GeneratedDraft (..),
    discoverContent,
    generateDraft,
    reviseDraft,
    extractText,
    extractTokenCount,
    extractGroundingChunks,
    resolveRedirectUrl,
    mergeWithChunks,
    followRedirect,
    parseTagsLine,
  )
where

import Control.Exception (SomeException, try)
import Data.Aeson
import Data.Aeson.Types (Parser, parseMaybe)
import qualified Data.ByteString.Lazy as LBS
import Data.FileEmbed (embedFile, makeRelativeToProject)
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import Data.Maybe (catMaybes, fromMaybe, isJust, listToMaybe, mapMaybe)
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as TE
import GHC.Generics (Generic)
import Network.HTTP.Client
  ( Manager,
    Request (..),
    RequestBody (..),
    httpLbs,
    parseRequest,
    responseBody,
    responseHeaders,
    responseStatus,
    responseTimeout,
    responseTimeoutMicro,
  )
import Network.HTTP.Types (statusCode)
import Orchestrator.TextUtils (splitTitle, toSlug)

-- ---------------------------------------------------------------------------
-- Types
-- ---------------------------------------------------------------------------

-- | Runtime configuration for the Gemini client.
data AiConfig = AiConfig
  { -- | Google AI API key (from environment, see https://aistudio.google.com/apikey).
    aiApiKey :: !Text,
    -- | Model identifier, e.g. @"gemini-2.5-flash"@ or @"gemini-2.5-pro"@.
    aiModel :: !Text,
    aiManager :: !Manager
  }

-- | A piece of web content discovered by the AI.
data DiscoveredContent = DiscoveredContent
  { dcTitle :: !Text,
    dcUrl :: !Text,
    dcSummary :: !Text,
    -- | Optional subject name hint; matched against the Subject table at ingest time.
    dcSubject :: !(Maybe Text)
  }
  deriving (Show, Eq, Generic)

-- | Raw model output from the discovery prompt (no URL — URLs come from
-- grounding chunks via 'mergeWithChunks').
data ModelItem = ModelItem
  { miTitle :: !Text,
    miSummary :: !Text,
    miSubject :: !(Maybe Text)
  }
  deriving (Show, Eq, Generic)

instance FromJSON ModelItem where
  parseJSON = withObject "ModelItem" $ \o ->
    ModelItem
      <$> o .: "title"
      <*> o .: "summary"
      <*> o .:? "subject"

instance FromJSON DiscoveredContent where
  parseJSON = withObject "DiscoveredContent" $ \o ->
    DiscoveredContent
      <$> o .: "title"
      <*> o .: "url"
      <*> o .: "summary"
      <*> o .:? "subject"

instance ToJSON DiscoveredContent where
  toJSON DiscoveredContent {..} =
    object
      [ "title" .= dcTitle,
        "url" .= dcUrl,
        "summary" .= dcSummary,
        "subject" .= dcSubject
      ]

-- | A post draft generated by the AI from one or more content sources.
data GeneratedDraft = GeneratedDraft
  { gdTitle :: !Text,
    -- | Git branch name to push the draft to, e.g. @"draft/my-post-title"@.
    gdBranch :: !Text,
    -- | Markdown body (without the leading TAGS line; Hugo front-matter is
    -- added separately by 'renderHugoPost').
    gdBody :: !Text,
    -- | Tags extracted from the leading @TAGS:@ line of the AI output.
    gdTags :: ![Text],
    -- | Total tokens consumed by this generation call
    --   (@usageMetadata.totalTokenCount@ in the Gemini response).
    gdTokensUsed :: !Int
  }
  deriving (Show, Eq, Generic)

instance FromJSON GeneratedDraft where
  parseJSON = withObject "GeneratedDraft" $ \o ->
    GeneratedDraft
      <$> o .: "gdTitle"
      <*> o .: "gdBranch"
      <*> o .: "gdBody"
      <*> (o .:? "gdTags" .!= [])
      <*> (o .:? "gdTokensUsed" .!= 0)

instance ToJSON GeneratedDraft where
  toJSON GeneratedDraft {..} =
    object
      [ "gdTitle" .= gdTitle,
        "gdBranch" .= gdBranch,
        "gdBody" .= gdBody,
        "gdTags" .= gdTags,
        "gdTokensUsed" .= gdTokensUsed
      ]

-- ---------------------------------------------------------------------------
-- Embedded prompts
-- ---------------------------------------------------------------------------

-- | Prompt for 'discoverContent' – embedded from @prompts/discover_content.txt@.
discoverPrompt :: Text
discoverPrompt = TE.decodeUtf8 $(makeRelativeToProject "prompts/discover_content.txt" >>= embedFile)

-- | Prompt template for 'generateDraft' – embedded from @prompts/generate_draft.txt@.
-- The literal @{{SOURCES}}@ is replaced at runtime with the formatted sources list.
draftPromptTemplate :: Text
draftPromptTemplate = TE.decodeUtf8 $(makeRelativeToProject "prompts/generate_draft.txt" >>= embedFile)

-- | Prompt template for 'reviseDraft' – embedded from @prompts/revise_draft.txt@.
-- The literals @{{DRAFT}}@ and @{{FEEDBACK}}@ are replaced at runtime.
revisePromptTemplate :: Text
revisePromptTemplate = TE.decodeUtf8 $(makeRelativeToProject "prompts/revise_draft.txt" >>= embedFile)

-- ---------------------------------------------------------------------------
-- Internal HTTP helpers
-- ---------------------------------------------------------------------------

-- | Build the @generateContent@ endpoint URL for the configured model.
generateContentUrl :: AiConfig -> String
generateContentUrl AiConfig {..} =
  "https://generativelanguage.googleapis.com/v1beta/models/"
    <> T.unpack aiModel
    <> ":generateContent?key="
    <> T.unpack aiApiKey

-- | POST a JSON body to the Gemini @generateContent@ endpoint and return the
--   raw response bytes.
postGemini :: AiConfig -> Value -> IO LBS.ByteString
postGemini cfg body = do
  initReq <- parseRequest (generateContentUrl cfg)
  let req =
        initReq
          { method = "POST",
            requestBody = RequestBodyLBS (encode body),
            requestHeaders = [("Content-Type", "application/json")],
            responseTimeout = responseTimeoutMicro (180 * 1_000_000)
          }
  responseBody <$> httpLbs req (aiManager cfg)

-- | POST a request body to Gemini and return the extracted text and total
-- token count, raising an 'IOError' on HTTP errors, API error responses, or
-- missing content.
callGemini :: AiConfig -> Value -> IO (Text, Int)
callGemini cfg body = do
  respBody <- postGemini cfg body
  case eitherDecode respBody of
    Left err -> ioError (userError $ "Gemini HTTP response parse error: " <> err)
    Right v -> do
      checkGeminiError v
      case extractText v of
        Nothing -> ioError (userError "Gemini: could not extract text from response")
        Just txt -> pure (txt, extractTokenCount v)

-- | Build a @contents@ array with a single user turn.
userContents :: Text -> Value
userContents prompt =
  object
    [ "role" .= ("user" :: Text),
      "parts" .= [object ["text" .= prompt]]
    ]

-- | Extract @usageMetadata.totalTokenCount@ from a Gemini response.
-- Returns 0 when the field is absent (e.g. in grounded-search responses).
extractTokenCount :: Value -> Int
extractTokenCount = fromMaybe 0 . parseMaybe go
  where
    go = withObject "GeminiResponse" $ \o -> do
      usage <- o .: "usageMetadata"
      usage .: "totalTokenCount"

-- | Extract the text payload from the first candidate's first part.
--   Gemini wraps generated content in:
--   @candidates[0].content.parts[0].text@
extractText :: Value -> Maybe Text
extractText = parseMaybe go
  where
    go = withObject "GeminiResponse" $ \o -> do
      candidates <- o .: "candidates"
      case candidates of
        [] -> fail "no candidates in Gemini response"
        (c : _) -> do
          content <- c .: "content"
          parts <- content .: "parts"
          case parts of
            [] -> fail "no parts in Gemini candidate"
            (p : _) -> p .: "text"

-- | Decode a UTF-8 text value as JSON, returning an @IO@ error on failure.
decodeText :: (FromJSON a) => Text -> IO a
decodeText t =
  case eitherDecode (LBS.fromStrict (TE.encodeUtf8 t)) of
    Left err -> ioError (userError $ "JSON decode error: " <> err)
    Right v -> pure v

-- | If the Gemini response contains a top-level @{"error": ...}@ object,
-- throw an 'IOError' with the API error code and message so callers get
-- a useful diagnosis (e.g. 429 quota exhausted) instead of a generic
-- "could not extract text" failure.
checkGeminiError :: Value -> IO ()
checkGeminiError v =
  case parseMaybe extractError v of
    Nothing -> pure ()
    Just msg -> ioError (userError $ "Gemini API error: " <> T.unpack msg)
  where
    extractError = withObject "GeminiResponse" $ \o -> do
      errObj <- o .: "error"
      code <- errObj .: "code" :: Parser Int
      msg <- errObj .: "message"
      pure $ "HTTP " <> T.pack (show code) <> " — " <> msg

-- | Strip markdown code fences that Gemini sometimes wraps around JSON output.
-- Handles both @```json\n...\n```@ and bare @```\n...\n```@.
stripFences :: Text -> Text
stripFences t =
  let ls = T.lines t
      trimmed = case ls of
        (h : rest)
          | isJust (T.stripPrefix "```" h) ->
              case reverse rest of
                ("```" : body) -> reverse body
                _ -> rest
        _ -> ls
   in T.strip (T.unlines trimmed)

-- | Generation parameters shared by the draft and revision calls.
defaultGenerationConfig :: Value
defaultGenerationConfig =
  object
    [ "temperature" .= (0.7 :: Double),
      "maxOutputTokens" .= (8192 :: Int)
    ]

-- ---------------------------------------------------------------------------
-- Public API
-- ---------------------------------------------------------------------------

-- | Extract (chunkTitle, realUri) pairs from Gemini's grounding metadata.
--
-- When the @google_search@ grounding tool is active, Gemini embeds ephemeral
-- @vertexaisearch.cloud.google.com\/grounding-api-redirect\/...@ URLs in the
-- generated text, but the real, permanent source URLs are available in
-- @candidates[0].groundingMetadata.groundingChunks[].web.uri@.  This
-- function extracts them so they can be substituted back into the parsed items.
extractGroundingChunks :: Value -> [(Text, Text)]
extractGroundingChunks = fromMaybe [] . parseMaybe go
  where
    go = withObject "GeminiResponse" $ \o -> do
      candidates <- o .: "candidates"
      case candidates of
        [] -> pure []
        (c : _) -> do
          meta <- c .: "groundingMetadata"
          chunks <- meta .: "groundingChunks"
          mapM parseChunk chunks
    parseChunk = withObject "GroundingChunk" $ \o -> do
      web <- o .: "web"
      uri <- web .: "uri"
      title <- web .:? "title" .!= uri
      pure (title, uri)

-- | If a 'DiscoveredContent' item has an ephemeral redirect URL, attempt to
-- replace it with the matching real URL from the grounding chunk map.
-- Matching is done by case-insensitive substring containment against the
-- chunk titles.  If no match is found the original (redirect) URL is kept.
resolveRedirectUrl :: Map Text Text -> DiscoveredContent -> DiscoveredContent
resolveRedirectUrl chunkMap dc
  | not ("vertexaisearch" `T.isInfixOf` dcUrl dc) = dc
  | otherwise = dc {dcUrl = fromMaybe (dcUrl dc) (findMatch (dcTitle dc))}
  where
    findMatch modelTitle =
      listToMaybe
        [ uri
          | (chunkTitle, uri) <- Map.toList chunkMap,
            let a = T.toCaseFold chunkTitle
                b = T.toCaseFold modelTitle,
            a `T.isInfixOf` b || b `T.isInfixOf` a
        ]

-- | Pair each 'ModelItem' with the best-matching grounding chunk to obtain a
-- real, permanent source URL.  Items with no matching chunk are dropped.
--
-- Matching uses keyword overlap: at least one significant word (five or more
-- characters) from either title must appear as a substring of the other
-- (case-insensitive).
mergeWithChunks :: [(Text, Text)] -> [ModelItem] -> [DiscoveredContent]
mergeWithChunks chunks = mapMaybe matchItem
  where
    matchItem mi =
      case findChunk (miTitle mi) of
        Nothing -> Nothing
        Just (_, uri) ->
          Just $ DiscoveredContent (miTitle mi) uri (miSummary mi) (miSubject mi)

    findChunk modelTitle =
      listToMaybe
        [ chunk
          | chunk@(chunkTitle, _) <- chunks,
            overlaps (T.toCaseFold modelTitle) (T.toCaseFold chunkTitle)
        ]

    overlaps a b =
      any (\w -> T.length w >= 5 && w `T.isInfixOf` b) (T.words a)
        || any (\w -> T.length w >= 5 && w `T.isInfixOf` a) (T.words b)

-- | Follow a single HTTP redirect and return the resolved permanent URL.
--
-- Makes a GET request with redirect-following disabled (@redirectCount = 0@)
-- and reads the @Location@ response header.  This resolves ephemeral
-- @vertexaisearch.cloud.google.com\/grounding-api-redirect\/...@ URLs to the
-- real article URL while the redirect token is still valid (i.e. immediately
-- after the Gemini API call that produced it).
--
-- Non-redirect URLs (no @vertexaisearch@ substring) are returned unchanged.
-- If the server returns no @Location@ header the original URL is kept.
followRedirect :: Manager -> Text -> IO Text
followRedirect mgr url
  | not ("vertexaisearch" `T.isInfixOf` url) = pure url
  | otherwise = do
      req <- parseRequest (T.unpack url)
      resp <- httpLbs req {redirectCount = 0} mgr
      pure $ maybe url TE.decodeUtf8 (lookup "Location" (responseHeaders resp))

-- | Verify that a URL resolves to a 200 response.
--
-- Issues a GET request and returns 'True' only when the HTTP status code is
-- 200.  Any network error or non-200 status yields 'False', so a single
-- broken URL does not abort the whole discovery batch.
checkUrl :: Manager -> Text -> IO Bool
checkUrl mgr url = do
  result <- (try :: IO Int -> IO (Either SomeException Int)) $ do
    req <- parseRequest (T.unpack url)
    resp <- httpLbs req mgr
    pure $ statusCode (responseStatus resp)
  pure $ case result of
    Right 200 -> True
    _ -> False

-- | Ask Gemini (with Google Search grounding) to discover recent, relevant
--   content and return it as a structured list.
--
-- The model provides redirect URLs for each item.  These are followed
-- immediately (while still valid) via 'followRedirect' to obtain the real,
-- permanent source URLs.  The HTML body of each resolved URL is then fetched
-- generator.
discoverContent :: AiConfig -> IO [DiscoveredContent]
discoverContent cfg = do
  (txt, _) <- callGemini cfg requestBody'
  items <- decodeText (stripFences txt) :: IO [DiscoveredContent]
  results <- mapM (resolveItem (aiManager cfg)) items
  pure (catMaybes results)
  where
    resolveItem mgr dc = do
      realUrl <- followRedirect mgr (dcUrl dc)
      -- Discard items whose URL is still on the vertexaisearch proxy domain
      -- (redirect failed) or whose resolved URL returns a non-200 status.
      if "vertexaisearch" `T.isInfixOf` realUrl
        then pure Nothing
        else do
          ok <- checkUrl mgr realUrl
          pure $ if ok then Just dc {dcUrl = realUrl} else Nothing
    -- google_search grounding is incompatible with responseMimeType/responseSchema
    -- JSON mode; the prompt instructs the model to return JSON directly.
    requestBody' =
      object
        [ "contents" .= [userContents discoverPrompt],
          "tools" .= [object ["google_search" .= object []]]
        ]

-- | Ask Gemini to write a full Markdown blog post draft based on the provided
--   content sources.
generateDraft :: AiConfig -> [DiscoveredContent] -> IO GeneratedDraft
generateDraft cfg sources = do
  (mdText, tokensUsed) <- callGemini cfg requestBody'
  let (tags, body) = parseTagsLine mdText
      (title, _) = splitTitle body
  pure GeneratedDraft {gdTitle = title, gdBranch = "draft/" <> toSlug title, gdBody = body, gdTags = tags, gdTokensUsed = tokensUsed}
  where
    sourcesBlock = T.unlines $ zipWith formatSource ([1 ..] :: [Int]) sources
    formatSource i dc =
      T.pack (show i)
        <> ". **"
        <> dcTitle dc
        <> "**\n   URL: "
        <> dcUrl dc
        <> "\n   "
        <> dcSummary dc
    prompt = T.replace "{{SOURCES}}" sourcesBlock draftPromptTemplate
    requestBody' =
      object
        [ "contents" .= [userContents prompt],
          "generationConfig" .= defaultGenerationConfig
        ]

-- | Ask Gemini to revise an existing draft based on reviewer feedback.
--
-- The returned 'GeneratedDraft' has the same 'gdBranch' derived from the
-- (possibly updated) title in the revised content.
reviseDraft :: AiConfig -> Text -> Text -> IO GeneratedDraft
reviseDraft cfg currentBody feedback = do
  (mdText, tokensUsed) <- callGemini cfg requestBody'
  let (tags, body) = parseTagsLine mdText
      (title', _) = splitTitle body
  pure GeneratedDraft {gdTitle = title', gdBranch = "draft/" <> toSlug title', gdBody = body, gdTags = tags, gdTokensUsed = tokensUsed}
  where
    prompt =
      T.replace "{{DRAFT}}" currentBody $
        T.replace "{{FEEDBACK}}" feedback revisePromptTemplate
    requestBody' =
      object
        [ "contents" .= [userContents prompt],
          "generationConfig" .= defaultGenerationConfig
        ]

-- ---------------------------------------------------------------------------
-- Utilities
-- ---------------------------------------------------------------------------

-- | Parse and remove a leading @TAGS: tag1, tag2, ...@ line from AI output.
-- Returns the list of trimmed tags (empty if no TAGS line) and the remaining
-- body text with leading whitespace stripped.
--
-- The Gemini draft prompt instructs the model to write exactly this line
-- before the H1 title so we can reliably extract structured tags without
-- a second API call.
parseTagsLine :: Text -> ([Text], Text)
parseTagsLine txt = case T.lines txt of
  (l : rest)
    | Just raw <- T.stripPrefix "TAGS:" l ->
        let tags = filter (not . T.null) . map T.strip . T.splitOn "," $ raw
         in (tags, T.strip (T.unlines rest))
  _ -> ([], txt)
