{-# LANGUAGE TemplateHaskell #-}

module Orchestrator.AI.Client
  ( AiConfig (..),
    -- | Re-exported from 'Orchestrator.AI.Client.Internal'.
    DiscoveredContent (..),
    -- | Re-exported from 'Orchestrator.AI.Client.Internal'.
    ModelItem (..),
    GeneratedDraft (..),
    ReviseRequest (..),
    discoverContent,
    generateDraft,
    generateCustomDraft,
    reviseDraft,
    isRateLimitError,
    isFallbackError,
    tryModelsInOrder,
  )
where

import Control.Exception (SomeException, displayException, throwIO, try)
import Data.Aeson
import Data.Aeson.Types (Parser, parseMaybe)
import qualified Data.ByteString.Lazy as LBS
import Data.FileEmbed (embedFile, makeRelativeToProject)
import Data.List (isInfixOf)
import Data.Maybe (catMaybes, isJust)
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as TE
import GHC.Generics (Generic)
import Network.HTTP.Client
  ( Manager,
    Request (..),
    RequestBody (..),
    httpLbs,
    parseRequest,
    responseBody,
    responseStatus,
    responseTimeout,
    responseTimeoutMicro,
  )
import Network.HTTP.Types (statusCode)
import Orchestrator.AI.Client.Internal
import Orchestrator.IOUtils (logMsg)
import Orchestrator.TextUtils (splitTitle, toSlug)

-- ---------------------------------------------------------------------------
-- Types
-- ---------------------------------------------------------------------------

-- | Runtime configuration for the Gemini client.
data AiConfig = AiConfig
  { -- | Google AI API key (from environment, see https://aistudio.google.com/apikey).
    aiApiKey :: !Text,
    -- | Ordered list of model identifiers to try, highest-priority first.
    -- When a model returns a rate-limit error (HTTP 429 / RESOURCE_EXHAUSTED)
    -- the next model in the list is attempted automatically.
    aiModels :: ![Text],
    aiManager :: !Manager
  }

-- | A post draft generated by the AI from one or more content sources.
data GeneratedDraft = GeneratedDraft
  { gdTitle :: !Text,
    -- | Git branch name to push the draft to, e.g. @"draft/my-post-title"@.
    gdBranch :: !Text,
    -- | English Markdown body (without the leading TAGS line; Hugo front-matter
    -- is added separately by 'renderHugoPost').
    gdBodyEn :: !Text,
    -- | Brazilian Portuguese Markdown body.
    gdBodyPtBr :: !Text,
    -- | Tags extracted from the leading @TAGS:@ line of the AI output.
    gdTags :: ![Text],
    -- | Total tokens consumed by this generation call
    --   (@usageMetadata.totalTokenCount@ in the Gemini response).
    gdTokensUsed :: !Int
  }
  deriving (Show, Eq, Generic)

instance FromJSON GeneratedDraft where
  parseJSON = withObject "GeneratedDraft" $ \o ->
    GeneratedDraft
      <$> o .: "gdTitle"
      <*> o .: "gdBranch"
      <*> o .: "gdBodyEn"
      <*> o .: "gdBodyPtBr"
      <*> (o .:? "gdTags" .!= [])
      <*> (o .:? "gdTokensUsed" .!= 0)

instance ToJSON GeneratedDraft where
  toJSON GeneratedDraft {..} =
    object
      [ "gdTitle" .= gdTitle,
        "gdBranch" .= gdBranch,
        "gdBodyEn" .= gdBodyEn,
        "gdBodyPtBr" .= gdBodyPtBr,
        "gdTags" .= gdTags,
        "gdTokensUsed" .= gdTokensUsed
      ]

-- ---------------------------------------------------------------------------
-- Embedded prompts
-- ---------------------------------------------------------------------------

-- | Prompt for 'discoverContent' – embedded from @prompts/discover_content.txt@.
discoverPrompt :: Text
discoverPrompt = TE.decodeUtf8 $(makeRelativeToProject "prompts/discover_content.txt" >>= embedFile)

-- | Prompt template for 'generateDraft' – embedded from @prompts/generate_draft.txt@.
-- The literal @{{SOURCES}}@ is replaced at runtime with the formatted sources list.
draftPromptTemplate :: Text
draftPromptTemplate = TE.decodeUtf8 $(makeRelativeToProject "prompts/generate_draft.txt" >>= embedFile)

-- | Prompt template for 'reviseDraft' – embedded from @prompts/revise_draft.txt@.
-- The literals @{{DRAFT_EN}}@, @{{DRAFT_PTBR}}@, and @{{FEEDBACK}}@ are replaced at runtime.
revisePromptTemplate :: Text
revisePromptTemplate = TE.decodeUtf8 $(makeRelativeToProject "prompts/revise_draft.txt" >>= embedFile)

-- | Prompt template for 'generateCustomDraft' – embedded from @prompts/custom_post.txt@.
-- The literals @{{TITLE_HINT}}@ and @{{INSTRUCTIONS}}@ are replaced at runtime.
customPostPromptTemplate :: Text
customPostPromptTemplate = TE.decodeUtf8 $(makeRelativeToProject "prompts/custom_post.txt" >>= embedFile)

-- ---------------------------------------------------------------------------
-- Internal HTTP helpers
-- ---------------------------------------------------------------------------

-- | Build the @generateContent@ endpoint URL for a specific model.
generateContentUrl :: AiConfig -> Text -> String
generateContentUrl AiConfig {..} model =
  "https://generativelanguage.googleapis.com/v1beta/models/"
    <> T.unpack model
    <> ":generateContent?key="
    <> T.unpack aiApiKey

-- | POST a JSON body to the Gemini @generateContent@ endpoint for a specific
-- model and return the raw response bytes.
postGemini :: AiConfig -> Text -> Value -> IO LBS.ByteString
postGemini cfg model body = do
  initReq <- parseRequest (generateContentUrl cfg model)
  let req =
        initReq
          { method = "POST",
            requestBody = RequestBodyLBS (encode body),
            requestHeaders = [("Content-Type", "application/json")],
            responseTimeout = responseTimeoutMicro (180 * 1_000_000)
          }
  responseBody <$> httpLbs req (aiManager cfg)

-- | Returns 'True' when the exception indicates a Gemini rate-limit error
-- (HTTP 429 or RESOURCE_EXHAUSTED).  Used by 'tryModelsInOrder' to decide
-- whether to fall through to the next model.
isRateLimitError :: SomeException -> Bool
isRateLimitError ex =
  let msg = displayException ex
   in "429" `isInfixOf` msg || "RESOURCE_EXHAUSTED" `isInfixOf` msg

-- | Returns 'True' for any transient Gemini error that warrants falling
-- through to the next model: rate limits and empty responses.
-- An empty response (finishReason=STOP with no text) can occur when a
-- model does not fully support grounded search; a more capable model in
-- the priority list should succeed.
isFallbackError :: SomeException -> Bool
isFallbackError ex =
  isRateLimitError ex
    || "could not extract text from response" `isInfixOf` displayException ex

-- | Try each model from the priority list in order, falling through to the
-- next model on any transient error detected by 'isFallbackError'
-- (rate limits and empty/unsupported responses).
-- Raises an 'IOError' when all models are exhausted or a non-transient error
-- occurs.
tryModelsInOrder :: [Text] -> (Text -> IO a) -> IO a
tryModelsInOrder [] _ = ioError (userError "Gemini: all configured models failed or are rate-limited")
tryModelsInOrder (model : rest) action = do
  result <- try (action model)
  case result of
    Right v -> pure v
    Left ex
      | isFallbackError ex -> do
          logMsg $ "[AI] Model " <> model <> " unavailable (" <> T.pack (displayException (ex :: SomeException)) <> "), trying next..."
          tryModelsInOrder rest action
      | otherwise -> throwIO (ex :: SomeException)

-- | Call Gemini with a specific model and return the extracted text and total
-- token count, raising an 'IOError' on HTTP errors, API error responses, or
-- missing content.
callGeminiWith :: AiConfig -> Text -> Value -> IO (Text, Int)
callGeminiWith cfg model body = do
  respBody <- postGemini cfg model body
  case eitherDecode respBody of
    Left err -> ioError (userError $ "Gemini HTTP response parse error: " <> err)
    Right v -> do
      checkGeminiError v
      case extractText v of
        Nothing ->
          ioError . userError $
            "Gemini: could not extract text from response"
              <> maybe "" (\r -> " (finishReason=" <> T.unpack r <> ")") (extractFinishReason v)
        Just txt -> pure (txt, extractTokenCount v)

-- | POST a request body to Gemini, trying models from 'aiModels' in priority
-- order.  On a rate-limit error the next model is attempted automatically.
-- Raises an 'IOError' when all models are exhausted or a non-rate-limit error
-- occurs.
callGemini :: AiConfig -> Value -> IO (Text, Int)
callGemini cfg body =
  tryModelsInOrder (aiModels cfg) $ \model ->
    callGeminiWith cfg model body

-- | Build a @contents@ array with a single user turn.
userContents :: Text -> Value
userContents prompt =
  object
    [ "role" .= ("user" :: Text),
      "parts" .= [object ["text" .= prompt]]
    ]

-- | Decode a UTF-8 text value as JSON, returning an @IO@ error on failure.
decodeText :: (FromJSON a) => Text -> IO a
decodeText t =
  case eitherDecode (LBS.fromStrict (TE.encodeUtf8 t)) of
    Left err -> ioError (userError $ "JSON decode error: " <> err)
    Right v -> pure v

-- | If the Gemini response contains a top-level @{"error": ...}@ object,
-- throw an 'IOError' with the API error code and message so callers get
-- a useful diagnosis (e.g. 429 quota exhausted) instead of a generic
-- "could not extract text" failure.
checkGeminiError :: Value -> IO ()
checkGeminiError v =
  case parseMaybe extractError v of
    Nothing -> pure ()
    Just msg -> ioError (userError $ "Gemini API error: " <> T.unpack msg)
  where
    extractError = withObject "GeminiResponse" $ \o -> do
      errObj <- o .: "error"
      code <- errObj .: "code" :: Parser Int
      msg <- errObj .: "message"
      pure $ "HTTP " <> T.pack (show code) <> " — " <> msg

-- | Strip markdown code fences that Gemini sometimes wraps around JSON output.
-- Handles both @```json\n...\n```@ and bare @```\n...\n```@.
stripFences :: Text -> Text
stripFences t =
  let ls = T.lines t
      trimmed = case ls of
        (h : rest)
          | isJust (T.stripPrefix "```" h) ->
              case reverse rest of
                ("```" : body) -> reverse body
                _ -> rest
        _ -> ls
   in T.strip (T.unlines trimmed)

-- | Generation parameters shared by the draft and revision calls.
defaultGenerationConfig :: Value
defaultGenerationConfig =
  object
    [ "temperature" .= (0.7 :: Double),
      "maxOutputTokens" .= (16384 :: Int)
    ]

-- ---------------------------------------------------------------------------
-- Public API
-- ---------------------------------------------------------------------------

-- | Verify that a URL resolves to a 200 response.
--
-- Issues a GET request and returns 'True' only when the HTTP status code is
-- 200.  Any network error or non-200 status yields 'False', so a single
-- broken URL does not abort the whole discovery batch.
checkUrl :: Manager -> Text -> IO Bool
checkUrl mgr url = do
  result <- (try :: IO Int -> IO (Either SomeException Int)) $ do
    req <- parseRequest (T.unpack url)
    resp <- httpLbs req mgr
    pure $ statusCode (responseStatus resp)
  pure $ case result of
    Right 200 -> True
    _ -> False

-- | Ask Gemini (with Google Search grounding) to discover recent, relevant
--   content and return it as a structured list.
--
-- The @subjects@ list is read from the database by the caller and substituted
-- into the prompt template at runtime, so the search scope always reflects
-- what is in the Subject table rather than being hardcoded.
--
-- The model provides redirect URLs for each item.  These are followed
-- immediately (while still valid) via 'followRedirect' to obtain the real,
-- permanent source URLs.  The HTML body of each resolved URL is then fetched
-- generator.
discoverContent :: AiConfig -> [Text] -> IO (Int, [DiscoveredContent])
discoverContent cfg subjects = do
  (txt, tokensUsed) <- callGemini cfg requestBody'
  items <- decodeText (stripFences txt) :: IO [DiscoveredContent]
  results <- mapM (resolveItem (aiManager cfg)) items
  pure (tokensUsed, catMaybes results)
  where
    bullets = T.unlines ["  - " <> s | s <- subjects]
    names = T.intercalate ", " (map (\s -> "\"" <> s <> "\"") subjects)
    prompt =
      T.replace "{{SUBJECTS}}" bullets $
        T.replace "{{SUBJECT_NAMES}}" names discoverPrompt
    resolveItem mgr dc = do
      realUrl <- followRedirect mgr (dcUrl dc)
      -- Discard items whose URL is still on the vertexaisearch proxy domain
      -- (redirect failed) or whose resolved URL returns a non-200 status.
      if "vertexaisearch" `T.isInfixOf` realUrl
        then pure Nothing
        else do
          ok <- checkUrl mgr realUrl
          pure $ if ok then Just dc {dcUrl = realUrl} else Nothing
    -- google_search grounding is incompatible with responseMimeType/responseSchema
    -- JSON mode; the prompt instructs the model to return JSON directly.
    requestBody' =
      object
        [ "contents" .= [userContents prompt],
          "tools" .= [object ["google_search" .= object []]]
        ]

-- | Ask Gemini to write a full Markdown blog post draft based on the provided
--   content sources.  Returns both an English and a Brazilian Portuguese version.
generateDraft :: AiConfig -> [DiscoveredContent] -> IO GeneratedDraft
generateDraft cfg sources = do
  (mdText, tokensUsed) <- callGemini cfg requestBody'
  pure (assembleGeneratedDraft tokensUsed mdText)
  where
    sourcesBlock = T.unlines $ zipWith formatSource ([1 ..] :: [Int]) sources
    formatSource i dc =
      T.pack (show i)
        <> ". **"
        <> dcTitle dc
        <> "**\n   URL: "
        <> dcUrl dc
        <> "\n   "
        <> dcSummary dc
    prompt = T.replace "{{SOURCES}}" sourcesBlock draftPromptTemplate
    requestBody' =
      object
        [ "contents" .= [userContents prompt],
          "generationConfig" .= defaultGenerationConfig
        ]

-- | Input to 'reviseDraft'.
data ReviseRequest = ReviseRequest
  { -- | Current English Markdown body.
    rvBodyEn :: !Text,
    -- | Current Brazilian Portuguese Markdown body.
    rvBodyPtBr :: !Text,
    -- | Reviewer feedback to pass to the model.
    rvFeedback :: !Text
  }

-- | Ask Gemini to revise an existing bilingual draft based on reviewer feedback.
--
-- The returned 'GeneratedDraft' has the same 'gdBranch' derived from the
-- (possibly updated) title in the revised English content.
reviseDraft :: AiConfig -> ReviseRequest -> IO GeneratedDraft
reviseDraft cfg ReviseRequest {..} = do
  (mdText, tokensUsed) <- callGemini cfg requestBody'
  pure (assembleGeneratedDraft tokensUsed mdText)
  where
    prompt =
      T.replace "{{DRAFT_EN}}" rvBodyEn $
        T.replace "{{DRAFT_PTBR}}" rvBodyPtBr $
          T.replace "{{FEEDBACK}}" rvFeedback revisePromptTemplate
    requestBody' =
      object
        [ "contents" .= [userContents prompt],
          "generationConfig" .= defaultGenerationConfig
        ]

-- | Ask Gemini to write a bilingual blog post based on custom author instructions.
--
-- This is used for on-demand posts initiated from a Discord forum thread:
-- the thread title becomes the @titleHint@ and the first message becomes
-- @instructions@.  The AI may refine the title.  No source content is needed.
generateCustomDraft :: AiConfig -> Text -> Text -> IO GeneratedDraft
generateCustomDraft cfg titleHint instructions = do
  (mdText, tokensUsed) <- callGemini cfg requestBody'
  pure (assembleGeneratedDraft tokensUsed mdText)
  where
    prompt =
      T.replace "{{TITLE_HINT}}" titleHint $
        T.replace "{{INSTRUCTIONS}}" instructions customPostPromptTemplate
    requestBody' =
      object
        [ "contents" .= [userContents prompt],
          "generationConfig" .= defaultGenerationConfig
        ]

-- ---------------------------------------------------------------------------
-- Utilities
-- ---------------------------------------------------------------------------

-- | Assemble a 'GeneratedDraft' from a raw Gemini response text and token count.
-- Shared by 'generateDraft' and 'reviseDraft'.
assembleGeneratedDraft :: Int -> Text -> GeneratedDraft
assembleGeneratedDraft tokensUsed mdText =
  let (tags, bodyEn, bodyPtBr) = parseBilingualResponse mdText
      (title, _) = splitTitle bodyEn
   in GeneratedDraft
        { gdTitle = title,
          gdBranch = "draft/" <> toSlug title,
          gdBodyEn = bodyEn,
          gdBodyPtBr = bodyPtBr,
          gdTags = tags,
          gdTokensUsed = tokensUsed
        }

